dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - matplotlib
    - pandas
    - thinc
    - sklearn
    - Pillow
    - requests
    - xlsxwriter
    - openpyxl
    - xlwings
